#! /usr/bin/python

"""
Pentagonal numbers are generated by the formula, P(n) = n*(3*n-1)/2.
Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference 
are pentagonal and D = |Pk - Pj| is minimized

What is the value of D?
"""

pentnums = [(x*(3*x - 1))/2 for x in range(1000, 5000)]
print pentnums

diffpents = []
for i in pentnums:
    for j in pentnums:
        if i+j in pentnums and i-j in pentnums:
            diffpents.append((i,j))

print diffpents
